use windows::Win32::System::Threading::{
    PROCESS_POWER_THROTTLING_CURRENT_VERSION, PROCESS_POWER_THROTTLING_EXECUTION_SPEED,
    PROCESS_POWER_THROTTLING_STATE, THREAD_POWER_THROTTLING_CURRENT_VERSION,
    THREAD_POWER_THROTTLING_EXECUTION_SPEED, THREAD_POWER_THROTTLING_STATE,
};

const STATE_NONE: u32 = 0x0;

pub(crate) const PROCESS_THROTTLE: PROCESS_POWER_THROTTLING_STATE =
    PROCESS_POWER_THROTTLING_STATE {
        Version: PROCESS_POWER_THROTTLING_CURRENT_VERSION,
        ControlMask: PROCESS_POWER_THROTTLING_EXECUTION_SPEED,
        StateMask: PROCESS_POWER_THROTTLING_EXECUTION_SPEED,
    };

pub(crate) const PROCESS_UNTHROTTLE: PROCESS_POWER_THROTTLING_STATE =
    PROCESS_POWER_THROTTLING_STATE {
        Version: PROCESS_POWER_THROTTLING_CURRENT_VERSION,
        ControlMask: PROCESS_POWER_THROTTLING_EXECUTION_SPEED,
        StateMask: STATE_NONE,
    };

pub(crate) const PROCESS_RESTORE: PROCESS_POWER_THROTTLING_STATE = PROCESS_POWER_THROTTLING_STATE {
    Version: PROCESS_POWER_THROTTLING_CURRENT_VERSION,
    ControlMask: STATE_NONE,
    StateMask: STATE_NONE,
};

pub(crate) const THREAD_THROTTLE: THREAD_POWER_THROTTLING_STATE = THREAD_POWER_THROTTLING_STATE {
    Version: THREAD_POWER_THROTTLING_CURRENT_VERSION,
    ControlMask: THREAD_POWER_THROTTLING_EXECUTION_SPEED,
    StateMask: THREAD_POWER_THROTTLING_EXECUTION_SPEED,
};

pub(crate) const THREAD_UNTHROTTLE: THREAD_POWER_THROTTLING_STATE = THREAD_POWER_THROTTLING_STATE {
    Version: THREAD_POWER_THROTTLING_CURRENT_VERSION,
    ControlMask: THREAD_POWER_THROTTLING_EXECUTION_SPEED,
    StateMask: STATE_NONE,
};

pub(crate) const THREAD_RESTORE: THREAD_POWER_THROTTLING_STATE = THREAD_POWER_THROTTLING_STATE {
    Version: THREAD_POWER_THROTTLING_CURRENT_VERSION,
    ControlMask: STATE_NONE,
    StateMask: STATE_NONE,
};
