name: Build Releases
on:
  # only manually build
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    name: Release on ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            suffix: .exe
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            suffix: .exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
      - name: Prepare assets
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/fitgirl-ecoqos${{ matrix.suffix }} .
          tar -cvzf ${{ matrix.target }}.tar.gz LICENSE README.md fitgirl-ecoqos${{ matrix.suffix }}
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.target }}.tar.gz
          tag_name: nightly
          prerelease: false
          make_latest: true
