[package]
name = "listen-new-proc"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-lite = "2.6.0"
wmi = "0.17.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
